<?xml version="1.0"?>
<robot name="robot_arm" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="PI" value="3.14159265359"/>

    <xacro:property name="d_2djnt_h_L" value="0.143"/>
    <xacro:property name="d_2djnt_h_W" value="0.165"/>
    <xacro:property name="d_2djnt_h_H" value="0.158"/>
    <xacro:property name="d_2djnt_L" value="0.204"/>
    <xacro:property name="d_2djnt_W" value="0.145"/>
    <xacro:property name="d_2djnt_H" value="0.090"/>
    <xacro:property name="d_conn_L" value="0.076"/>
    <xacro:property name="d_conn_W" value="0.076"/>
    <xacro:property name="d_conn_H" value="0.076"/>
    <xacro:property name="d_L_len" value="0.900"/>
    <xacro:property name="d_L_rad" value="0.030"/>
    <xacro:property name="d_J12_L" value="0.12914"/>
    <xacro:property name="d_J12_W" value="0.076"/>
    <xacro:property name="d_J12_H" value="0.15705"/>
    <xacro:property name="d_J3_L" value="0.14614"/>
    <xacro:property name="d_J3_W" value="0.15705"/>
    <xacro:property name="d_J3_H" value="0.076"/>
    <xacro:property name="d_manip_mount_L" value="0.100"/>
    <xacro:property name="d_manip_mount_W" value="0.070"/>
    <xacro:property name="d_manip_mount_H" value="0.0935"/>
    <xacro:property name="d_mj1_L" value="0.0405"/>
    <xacro:property name="d_mj1_W" value="0.0405"/>
    <xacro:property name="d_mj1_H" value="0.020"/>
    <xacro:property name="d_mj2_L" value="0.058"/>
    <xacro:property name="d_mj2_W" value="0.0307"/>
    <xacro:property name="d_mj2_H" value="0.0436"/>
    <xacro:property name="d_mj3_L" value="0.058"/>
    <xacro:property name="d_mj3_W" value="0.0436"/>
    <xacro:property name="d_mj3_H" value="0.0307"/>

    <xacro:property name="m_L" value="0.395"/>
    <xacro:property name="m_J12" value="0.851"/>
    <xacro:property name="m_J3" value="0.982"/> <xacro:property name="m_conn" value="0.155"/>
    <xacro:property name="m_2djnt_h" value="1.780"/> <xacro:property name="m_2djnt" value="1.780"/> <xacro:property name="m_mj" value="0.039"/> <xacro:property name="m_manip_mount" value="0.170"/>

    <material name="red">
        <color rgba="${200/255} ${30/255} ${30/255} 1"/>
    </material>
    <material name="gray">
        <color rgba="${120/255} ${120/255} ${120/255} 1"/>
    </material>
    <material name="black">
        <color rgba="${20/255} ${20/255} ${20/255} 1"/>
    </material>
    <material name="purple">
        <color rgba="${150/255} ${50/255} ${200/255} 1"/>
    </material>

    <xacro:macro name="box_inertia" params="m x y z">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (y*y + z*z)}" ixy="0.0" ixz="0.0"
                     iyy="${(m/12) * (x*x + z*z)}" iyz="0.0"
                     izz="${(m/12) * (x*x + y*y)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h">
        <inertial>
            <mass value="${m}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0"
                     iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0"
                     izz="${(m/2) * (r*r)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="arm_link_macro" params="name">
        <link name="${name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
                <geometry>
                    <cylinder length="${d_L_len}" radius="${d_L_rad}"/>
                </geometry>
                <material name="gray"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
                <geometry>
                    <cylinder length="${d_L_len}" radius="${d_L_rad}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="${m_L}" r="${d_L_rad}" h="${d_L_len}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="arm_joint_macro" params="name L W H mass">
        <link name="${name}">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${L} ${W} ${H}"/>
                </geometry>
                <material name="red"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${L} ${W} ${H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${mass}" x="${L}" y="${W}" z="${H}"/>
        </link>
    </xacro:macro>

    <link name="base_link"/>

    ---

    <link name="2djnt_housing_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_2djnt_h_L} ${d_2djnt_h_W} ${d_2djnt_h_H}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_2djnt_h_L} ${d_2djnt_h_W} ${d_2djnt_h_H}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="${m_2djnt_h}" x="${d_2djnt_h_L}" y="${d_2djnt_h_W}" z="${d_2djnt_h_H}"/>
    </link>

    <joint name="base_to_2djnt_housing" type="fixed">
        <parent link="base_link"/>
        <child link="2djnt_housing_link"/>
        <origin xyz="0 0 -${d_2djnt_h_H/2}" rpy="0 0 0"/>
    </joint>

    ---

    <link name="2djnt_pitch_link"/>

    <joint name="2djnt_pitch_joint" type="revolute">
        <parent link="2djnt_housing_link"/>
        <child link="2djnt_pitch_link"/>
        <origin xyz="${-d_2djnt_h_L/2 - 0.059 + d_2djnt_L/2} 0 ${d_2djnt_h_H/2 - 0.080 - d_2djnt_H/2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${PI/2}" upper="${PI/2}" effort="100" velocity="1.0"/>
    </joint>

    <link name="2djnt_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_2djnt_L} ${d_2djnt_W} ${d_2djnt_H}"/>
            </geometry>
            <material name="red"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_2djnt_L} ${d_2djnt_W} ${d_2djnt_H}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="${m_2djnt}" x="${d_2djnt_L}" y="${d_2djnt_W}" z="${d_2djnt_H}"/>
    </link>

    <joint name="2djnt_roll_joint" type="revolute">
        <parent link="2djnt_pitch_link"/>
        <child link="2djnt_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit lower="-${PI/2}" upper="${PI/2}" effort="100" velocity="1.0"/>
    </joint>

    ---

    <link name="connector_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_conn_L} ${d_conn_W} ${d_conn_H}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_conn_L} ${d_conn_W} ${d_conn_H}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="${m_conn}" x="${d_conn_L}" y="${d_conn_W}" z="${d_conn_H}"/>
    </link>

    <joint name="2djnt_to_connector" type="fixed">
        <parent link="2djnt_link"/>
        <child link="connector_link"/>
        <origin xyz="${(d_2djnt_L/2 - 0.022) + d_conn_L/2} 0 ${d_2djnt_H/2 - 0.0225 - d_conn_H/2}" rpy="0 0 0"/>
    </joint>

    ---

    <xacro:arm_link_macro name="L1_link"/>
    <joint name="connector_to_L1" type="fixed">
        <parent link="connector_link"/>
        <child link="L1_link"/>
        <origin xyz="${d_conn_L/2 + d_L_len/2} 0 0" rpy="0 0 0"/>
    </joint>

    <xacro:arm_joint_macro name="J1_link" L="${d_J12_L}" W="${d_J12_W}" H="${d_J12_H}" mass="${m_J12}"/>
    <joint name="L1_to_J1" type="revolute">
        <parent link="L1_link"/>
        <child link="J1_link"/>
        <origin xyz="${d_L_len/2 + d_J12_L/2} 0 ${-0.038 + d_J12_H/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${PI}" upper="${PI}" effort="100" velocity="1.0"/>
    </joint>

    ---

    <xacro:arm_link_macro name="L2_link"/>
    <joint name="J1_to_L2" type="fixed">
        <parent link="J1_link"/>
        <child link="L2_link"/>
        <origin xyz="${(d_J12_L/2 - 0.04014) + d_L_len/2} 0 ${d_J12_H/2 - 0.038}" rpy="0 0 0"/>
    </joint>

    <xacro:arm_joint_macro name="J2_link" L="${d_J12_L}" W="${d_J12_W}" H="${d_J12_H}" mass="${m_J12}"/>
    <joint name="L2_to_J2" type="revolute">
        <parent link="L2_link"/>
        <child link="J2_link"/>
        <origin xyz="${d_L_len/2 + d_J12_L/2} 0 ${0.038 - d_J12_H/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${PI}" upper="${PI}" effort="100" velocity="1.0"/>
    </joint>

    ---

    <xacro:arm_link_macro name="L3_link"/>
    <joint name="J2_to_L3" type="fixed">
        <parent link="J2_link"/>
        <child link="L3_link"/>
        <origin xyz="${(d_J12_L/2 - 0.04014) + d_L_len/2} 0 ${-d_J12_H/2 + 0.038}" rpy="0 0 0"/>
    </joint>

    <xacro:arm_joint_macro name="J3_link" L="${d_J3_L}" W="${d_J3_W}" H="${d_J3_H}" mass="${m_J3}"/>
    <joint name="L3_to_J3" type="revolute">
        <parent link="L3_link"/>
        <child link="J3_link"/>
        <origin xyz="${d_L_len/2 + d_J3_L/2} ${-0.03805 + d_J3_W/2} 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${PI/2}" upper="${PI/2}" effort="100" velocity="1.0"/>
    </joint>

    ---

    <xacro:arm_link_macro name="L4_link"/>
    <joint name="J3_to_L4" type="fixed">
        <parent link="J3_link"/>
        <child link="L4_link"/>
        <origin xyz="${(d_J3_L/2 - 0.04014) + d_L_len/2} ${d_J3_W/2 - 0.038} 0" rpy="0 0 0"/>
    </joint>
    
    <link name="manip_mount_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_manip_mount_L} ${d_manip_mount_W} ${d_manip_mount_H}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${d_manip_mount_L} ${d_manip_mount_W} ${d_manip_mount_H}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="${m_manip_mount}" x="${d_manip_mount_L}" y="${d_manip_mount_W}" z="${d_manip_mount_H}"/>
    </link>

    <joint name="L4_to_manip_mount" type="fixed">
        <parent link="L4_link"/>
        <child link="manip_mount_link"/>
        <origin xyz="${d_L_len/2 + d_manip_mount_L/2} 0 ${0.042 - d_manip_mount_H/2}" rpy="0 0 0"/>
    </joint>

    ---

    <link name="mj1_link">
        <visual>
            <geometry>
                <box size="${d_mj1_L} ${d_mj1_W} ${d_mj1_H}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision><geometry><box size="${d_mj1_L} ${d_mj1_W} ${d_mj1_H}"/></geometry></collision>
        <xacro:box_inertia m="${m_mj}" x="${d_mj1_L}" y="${d_mj1_W}" z="${d_mj1_H}"/>
    </link>
    <joint name="mount_to_mj1" type="revolute">
        <parent link="manip_mount_link"/>
        <child link="mj1_link"/>
        <origin xyz="${(d_manip_mount_L/2 - 0.00875) - d_mj1_L/2} ${-d_manip_mount_W/2 - 0.0121 + d_mj1_W/2} ${(d_manip_mount_H/2 - 0.006) - d_mj1_H/2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${PI/2}" upper="${PI/2}" effort="50" velocity="1.5"/>
    </joint>

    <link name="mj2_link">
        <visual>
            <geometry>
                <box size="${d_mj2_L} ${d_mj2_W} ${d_mj2_H}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision><geometry><box size="${d_mj2_L} ${d_mj2_W} ${d_mj2_H}"/></geometry></collision>
        <xacro:box_inertia m="${m_mj}" x="${d_mj2_L}" y="${d_mj2_W}" z="${d_mj2_H}"/>
    </link>
    <joint name="mj1_to_mj2" type="revolute">
        <parent link="mj1_link"/>
        <child link="mj2_link"/>
        <origin xyz="${(d_mj1_L/2 + 0.0295) - d_mj2_L/2} ${-d_mj1_W/2 - d_mj2_W/2} ${(d_mj1_H/2 + 0.0091) - d_mj2_H/2}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="-${PI/2}" upper="${PI/2}" effort="50" velocity="1.5"/>
    </joint>

    <link name="mj3_link">
        <visual>
            <geometry>
                <box size="${d_mj3_L} ${d_mj3_W} ${d_mj3_H}"/>
            </geometry>
            <material name="purple"/>
        </visual>
        <collision><geometry><box size="${d_mj3_L} ${d_mj3_W} ${d_mj3_H}"/></geometry></collision>
        <xacro:box_inertia m="${m_mj}" x="${d_mj3_L}" y="${d_mj3_W}" z="${d_mj3_H}"/>
    </link>
    <joint name="mj2_to_mj3" type="revolute">
        <parent link="mj2_link"/>
        <child link="mj3_link"/>
        <origin xyz="${(-d_mj2_L/2 + 0.00025) + d_mj3_L/2} ${d_mj2_W/2 + 0.0053 - d_mj3_W/2} ${d_mj2_H/2 + d_mj3_H/2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="-${PI/2}" upper="${PI/2}" effort="50" velocity="1.5"/>
    </joint>
    
    <gazebo reference="2djnt_housing_link"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="2djnt_link"><material>Gazebo/Red</material></gazebo>
    <gazebo reference="connector_link"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="L1_link"><material>Gazebo/Gray</material></gazebo>
    <gazebo reference="J1_link"><material>Gazebo/Red</material></gazebo>
    <gazebo reference="L2_link"><material>Gazebo/Gray</material></gazebo>
    <gazebo reference="J2_link"><material>Gazebo/Red</material></gazebo>
    <gazebo reference="L3_link"><material>Gazebo/Gray</material></gazebo>
    <gazebo reference="J3_link"><material>Gazebo/Red</material></gazebo>
    <gazebo reference="L4_link"><material>Gazebo/Gray</material></gazebo>
    <gazebo reference="manip_mount_link"><material>Gazebo/Black</material></gazebo>
    <gazebo reference="mj1_link"><material>Gazebo/Purple</material></gazebo>
    <gazebo reference="mj2_link"><material>Gazebo/Purple</material></gazebo>
    <gazebo reference="mj3_link"><material>Gazebo/Purple</material></gazebo>

</robot>
