<?xml version="1.0"?>
<!--***************************************************************************
/// @file   arm.urdf.xacro
/// @brief  LIBRA-I arm model definition.
///
/// @author brice.c.aa
****************************************************************************-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Includes -->
    <xacro:include filename="$(find libra)/models/common/common.urdf.xacro" />
    
    <!-- Definition -->
    <xacro:macro name="spawn_arm" params="parent">

        <!-- ********************[ PROPERTIES ]******************** -->

        <!-- 2DJNT Connector (copied from libra1_2djnt.urdf.xacro) -->
        <xacro:property name="d_conn_arm_L" value="0.076"/>
        <xacro:property name="d_conn_arm_H" value="0.0985"/>
        
        <!-- Arm Links -->
        <xacro:property name="d_arm_link_L" value="0.900"/>
        <xacro:property name="d_arm_link_R" value="0.030"/>
        <xacro:property name="m_arm_link" value="0.395"/>

        <!-- Joint Connectors -->
        <xacro:property name="d_conn_outer_L" value="0.076"/>
        <xacro:property name="d_conn_outer_W" value="0.076"/>
        <xacro:property name="d_conn_outer_H" value="0.076"/>
        <xacro:property name="m_conn_outer" value="0.192"/>

        <xacro:property name="d_conn_inner_L" value="0.056"/>
        <xacro:property name="d_conn_inner_W" value="0.076"/>
        <xacro:property name="d_conn_inner_H" value="0.076"/>
        <xacro:property name="m_conn_inner" value="0.169"/>
    
        <xacro:property name="d_adapter_L" value="0.017"/>
        <xacro:property name="d_adapter_W" value="0.076"/>
        <xacro:property name="d_adapter_H" value="0.076"/>
        <xacro:property name="m_adapter" value="0.131"/>

        <!-- HEBI X8-16 Actuators -->
        <xacro:property name="d_hebi_L" value="0.110"/>
        <xacro:property name="d_hebi_W" value="0.073"/>
        <xacro:property name="d_hebi_H" value="0.0451"/>
        <xacro:property name="m_hebi" value="0.490"/>

        <!-- Arm Tip / Manipulator Mount -->
        <xacro:property name="d_arm_tip_L" value="0.100"/>
        <xacro:property name="d_arm_tip_W" value="0.070"/>
        <xacro:property name="d_arm_tip_H" value="0.0935"/>
        <xacro:property name="m_arm_tip" value="0.170"/>

        <!-- Manipulator Joints -->
        <xacro:property name="d_MJ1_L" value="0.0405"/>
        <xacro:property name="d_MJ1_W" value="0.0405"/>
        <xacro:property name="d_MJ1_H" value="0.020"/>

        <xacro:property name="d_MJ23_L" value="0.058"/>
        <xacro:property name="d_MJ23_W" value="0.0307"/>
        <xacro:property name="d_MJ23_H" value="0.0436"/>

        <xacro:property name="m_MJ" value="0.039"/>

        <!-- ********************[ MACROS ]******************** -->

        <xacro:macro name="link_macro" params="name">
            <link name="${name}">
                <visual>
                    <origin xyz="0 0 0" rpy="0 ${PI/2} ${PI/2}"/>
                    <geometry>
                        <mesh filename="package://libra/meshes/arm-link.stl" scale="0.001 0.001 0.001"/>
                    </geometry>
                    <material name="gray"/>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 ${PI/2} 0"/>
                    <geometry>
                        <cylinder length="${d_arm_link_L}" radius="${d_arm_link_R}"/>
                    </geometry>
                </collision>
                <xacro:cylinder_inertia m="${m_arm_link}" r="${d_arm_link_R}" h="${d_arm_link_L}"/>
            </link>
        </xacro:macro>

        <xacro:macro name="joint_subassembly_macro" params="name parent_name origin_xyz origin_rpy">
            <!-- Inbound Connection -->
            <link name="${name}_conn_outer_link">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="${d_conn_L} ${d_conn_W} ${d_conn_H}"/>
                        <!-- TODO
                        <mesh filename="package://libra/meshes/conn_inner.stl" scale="0.001 0.001 0.001"/>
                        -->
                    </geometry>
                    <material name="black"/>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="${d_conn_outer_L} ${d_conn_outer_W} ${d_conn_outer_H}"/>
                    </geometry>
                </collision>
                <xacro:box_inertia m="${m_conn_outer}" x="${d_conn_outer_L}" y="${d_conn_outer_W}" z="${d_conn_outer_H}"/>
            </link>
            <joint name="${parent_name}_to_${name}_conn_outer" type="fixed">
                <parent link="${parent_name}_link"/>
                <child link="${name}_conn_outer_link"/>
                <origin xyz="${origin_xyz}" rpy="${origin_rpy}"/>
            </joint>

            <!-- Actuator -->
            <link name="${name}_hebi_link">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="${d_hebi_L} ${d_hebi_W} ${d_hebi_H}"/>
                        <!-- TODO
                        <mesh filename="package://libra/meshes/hebi_x8-16.stl" scale="0.001 0.001 0.001"/>
                        -->
                    </geometry>
                    <material name="red"/>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="${d_hebi_L} ${d_hebi_W} ${d_hebi_H}"/>
                    </geometry>
                </collision>
                <xacro:box_inertia m="${m_hebi}" x="${d_hebi_L}" y="${d_hebi_W}" z="${d_hebi_H}"/>
            </link>
            <joint name="${name}_conn_outer_to_${name}_hebi" type="fixed">
                <parent link="${name}_conn_outer_link"/>
                <child link="${name}_hebi_link"/>
                <origin xyz="${d_conn_outer_L/2 + 0.05314 - d_hebi_L/2} 0 ${-d_conn_outer_H/2 + 0.036 + d_hebi_H/2}" rpy="0 0 0"/>
            </joint>

            <!-- Outbound Connection -->
            <link name="${name}_conn_inner_link">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="${d_conn_L} ${d_conn_W} ${d_conn_H}"/>
                        <!-- TODO
                        <mesh filename="package://libra/meshes/conn_outer.stl" scale="0.001 0.001 0.001"/>
                        -->
                    </geometry>
                    <material name="black"/>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <box size="${d_conn_inner_L} ${d_conn_inner_W} ${d_conn_inner_H}"/>
                    </geometry>
                </collision>
                <xacro:box_inertia m="${m_conn_inner}" x="${d_conn_inner_L}" y="${d_conn_inner_W}" z="${d_conn_inner_H}"/>
            </link>
            <joint name="${name}_hebi_to_${name}_conn_inner" type="revolute">
                <parent link="${name}_hebi_link"/>
                <child link="${name}_conn_inner_link"/>
                <origin xyz="${d_hebi_L/2 - 0.04014 - d_conn_inner_L/2} 0 ${d_hebi_H/2 + d_conn_inner_H/2}" rpy="0 0 0"/>
                <axis xyz="0 0 1"/>  <!-- Although this defines a yaw joint, it can be changed by providing a non-zero origin_rpy (see J3) -->
                <limit lower="-${PI}" upper="${PI}" effort="100" velocity="1.0"/>
            </joint>
        </xacro:macro>

        <!-- ********************[ LINKS ]******************** -->
        <!-- NOTE
            X = forward/red, Y = left/green, Z = upwards/blue
        -->

        <!-- Arm Segment #1 -->
        <xacro:link_macro name="L1_link"/>
        <joint name="parent_to_L1" type="fixed">
            <parent link="${parent}"/>
            <child link="L1_link"/>
            <origin xyz="${d_conn_arm_L/2 + d_arm_link_L/2} 0 -${d_conn_arm_H/2 - 0.038}" rpy="0 0 0"/>
        </joint>

        <xacro:joint_subassembly_macro name="J1" parent_name="L1"
            origin_xyz="${d_arm_link_L/2 + d_conn_outer_L/2} 0 0" origin_rpy="0 0 0"/>

        ---

        <!-- Arm Segment #2 -->
        <xacro:link_macro name="L2_link"/>
        <joint name="J1_to_L2" type="fixed">
            <parent link="J1_conn_inner_link"/>
            <child link="L2_link"/>
            <origin xyz="${d_conn_inner_L/2 + d_arm_link_L/2} 0 0" rpy="0 0 0"/>
        </joint>

        <xacro:joint_subassembly_macro name="J2" parent_name="L2"
            origin_xyz="${d_arm_link_L/2 + d_conn_outer_L/2} 0 0" origin_rpy="${PI} 0 0"/>

        ---

        <!-- Arm Segment #3 -->
        <xacro:link_macro name="L3_link"/>
        <joint name="J2_to_L3" type="fixed">
            <parent link="J2_conn_inner_link"/>
            <child link="L3_link"/>
            <origin xyz="${d_conn_inner_L/2 + d_arm_link_L/2} 0 0" rpy="0 0 0"/>
        </joint>

        <link name="J3_conn_adapter_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_adapter_L} ${d_adapter_W} ${d_adapter_H}"/>
                    <!-- TODO
                    <mesh filename="package://libra/meshes/conn_adapter.stl" scale="0.001 0.001 0.001"/>
                    -->
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_adapter_L} ${d_adapter_W} ${d_adapter_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_adapter}" x="${d_adapter_L}" y="${d_adapter_W}" z="${d_adapter_H}"/>
        </link>
        <joint name="L3_to_J3_conn_adapter" type="fixed">
            <parent link="L3_link"/>
            <child link="J3_conn_adapter_link"/>
            <origin xyz="${d_arm_link_L/2 + d_adapter_L/2} 0 0" rpy="0 0 0"/>
        </joint>

        <xacro:joint_subassembly_macro name="J3" parent_name="J3_conn_adapter"
            origin_xyz="${d_adapter_L/2 + d_conn_outer_L/2} 0 0" origin_rpy="${PI/2} 0 0"/>

        ---

        <!-- Arm Segment #4 -->
        <xacro:link_macro name="L4_link"/>
        <joint name="J3_to_L4" type="fixed">
            <parent link="J3_conn_inner_link"/>
            <child link="L4_link"/>
            <origin xyz="${d_conn_inner_L/2 + d_arm_link_L/2} 0 0" rpy="${PI/2} 0 0"/>
        </joint>
        
        <link name="arm_tip_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_arm_tip_L} ${d_arm_tip_W} ${d_arm_tip_H}"/>
                    <!-- TODO
                    <mesh filename="package://libra/meshes/arm-tip.stl" scale="0.001 0.001 0.001"/>
                    -->
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_arm_tip_L} ${d_arm_tip_W} ${d_arm_tip_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_arm_tip}" x="${d_arm_tip_L}" y="${d_arm_tip_W}" z="${d_arm_tip_H}"/>
        </link>
        <joint name="L4_to_arm_tip" type="fixed">
            <parent link="L4_link"/>
            <child link="arm_tip_link"/>
            <origin xyz="${d_arm_link_L/2 + d_arm_tip_L/2} 0 ${0.042 - d_arm_tip_H/2}" rpy="0 0 0"/>
        </joint>

        ---

        <!-- Manipulator Joints -->
        <link name="mj1_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_MJ1_L} ${d_MJ1_W} ${d_MJ1_H}"/>
                    <!-- TODO
                    <mesh filename="package://libra/meshes/manip-j1.stl" scale="0.001 0.001 0.001"/>
                    -->
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_MJ1_L} ${d_MJ1_W} ${d_MJ1_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_MJ}" x="${d_MJ1_L}" y="${d_MJ1_W}" z="${d_MJ1_H}"/>
        </link>
        <joint name="arm_tip_to_MJ1" type="revolute">
            <parent link="arm_tip_link"/>
            <child link="mj1_link"/>
            <origin xyz="${(d_arm_tip_L/2 - 0.00875) - d_MJ1_L/2} ${-d_arm_tip_W/2 - 0.0121 + d_MJ1_W/2} ${(d_arm_tip_H/2 - 0.006) - d_MJ1_H/2}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-${PI/2}" upper="${PI/2}" effort="50" velocity="1.5"/>
        </joint>

        <link name="mj2_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_MJ23_L} ${d_MJ23_W} ${d_MJ23_H}"/>
                    <!-- TODO
                    <mesh filename="package://libra/meshes/manip-j2_3.stl" scale="0.001 0.001 0.001"/>
                    -->
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_MJ23_L} ${d_MJ23_W} ${d_MJ23_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_MJ}" x="${d_MJ23_L}" y="${d_MJ23_W}" z="${d_MJ23_H}"/>
        </link>
        <joint name="mj1_to_MJ2" type="revolute">
            <parent link="mj1_link"/>
            <child link="mj2_link"/>
            <origin xyz="${(d_MJ1_L/2 + 0.0295) - d_MJ23_L/2} ${-d_MJ1_W/2 - d_MJ23_W/2} ${(d_MJ1_H/2 + 0.0091) - d_MJ23_H/2}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="-${PI/2}" upper="${PI/2}" effort="50" velocity="1.5"/>
        </joint>

        <link name="mj3_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_MJ23_L} ${d_MJ23_H} ${d_MJ23_W}"/>
                    <!-- TODO
                    <mesh filename="package://libra/meshes/manip-j2_3.stl" scale="0.001 0.001 0.001"/>
                    -->
                </geometry>
                <material name="purple"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${d_MJ23_L} ${d_MJ23_H} ${d_MJ23_W}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_MJ}" x="${d_MJ23_L}" y="${d_MJ23_H}" z="${d_MJ23_W}"/>
        </link>
        <joint name="mj2_to_mj3" type="revolute">
            <parent link="mj2_link"/>
            <child link="mj3_link"/>
            <origin xyz="${(-d_MJ23_L/2 + 0.00025) + d_MJ23_L/2} ${d_MJ23_W/2 + 0.0053 - d_MJ23_H/2} ${d_MJ23_H/2 + d_MJ23_W/2}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
            <limit lower="-${PI/2}" upper="${PI/2}" effort="50" velocity="1.5"/>
        </joint>

        <!-- ********************[ GAZEBO CONFIG ]******************** -->

        <gazebo reference="L1_link"><material>Gazebo/Gray</material></gazebo>
        <gazebo reference="J1_link"><material>Gazebo/Red</material></gazebo>
        <gazebo reference="L2_link"><material>Gazebo/Gray</material></gazebo>
        <gazebo reference="J2_link"><material>Gazebo/Red</material></gazebo>
        <gazebo reference="L3_link"><material>Gazebo/Gray</material></gazebo>
        <gazebo reference="J3_link"><material>Gazebo/Red</material></gazebo>
        <gazebo reference="L4_link"><material>Gazebo/Gray</material></gazebo>
        <gazebo reference="arm_tip_link"><material>Gazebo/Black</material></gazebo>
        <gazebo reference="mj1_link"><material>Gazebo/Purple</material></gazebo>
        <gazebo reference="mj2_link"><material>Gazebo/Purple</material></gazebo>
        <gazebo reference="mj3_link"><material>Gazebo/Purple</material></gazebo>
        
    </xacro:macro>
</robot>
