<?xml version="1.0"?>
<!--***************************************************************************
/// @file   sensor_suite.urdf.xacro
/// @brief  LIBRA-I sensor suite model definition.
///
/// @author brice.c.aa
****************************************************************************-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Includes -->
    <xacro:include filename="$(find libra)/models/common/common.urdf.xacro" />

    <!-- Definition -->
    <xacro:macro name="spawn_sensors" params="parent">

        <!-- ********************[ PROPERTIES ]******************** -->

        <!-- Mounts -->
        <xacro:property name="m_lidar_L" value="0.012514"/>
        <xacro:property name="m_lidar_W" value="0.100000"/>
        <xacro:property name="m_lidar_H" value="0.084000"/>
        <xacro:property name="m_lidar_m" value="0.009"/>

        <xacro:property name="m_camera_L" value="0.104349"/>
        <xacro:property name="m_camera_W" value="0.135861"/>
        <xacro:property name="m_camera_H" value="0.059941"/>
        <xacro:property name="m_camera_m" value="0.056"/>

        <!-- 2D LIDAR (LightWare SF45-B) -->
        <xacro:property name="lidar_W" value="0.048462"/>
        <xacro:property name="lidar_H" value="0.043979"/>
        <xacro:property name="lidar_L" value="0.050587"/>
        <xacro:property name="lidar_m" value="0.058"/>

        <!-- RGB-D camera (Intel RealSense D456) -->
        <xacro:property name="camera_W" value="0.123999"/>
        <xacro:property name="camera_H" value="0.029093"/>
        <xacro:property name="camera_L" value="0.026004"/>
        <xacro:property name="camera_m" value="0.116"/>

        <!-- ********************[ LINKS ]******************** -->
        <!-- NOTE
            X = forward/red, Y = left/green, Z = upwards/blue
        -->

        <!-- Sensor Suite Base -->
        <link name="sensor_suite_base_link"/>
        <joint name="parent_to_sensor_suite_base" type="fixed">
            <parent link="${parent}"/>
            <child link="sensor_suite_base_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <!-- LIDAR Mount -->
        <link name="mount_lidar_link">
            <visual>
                <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <geometry>
                    <mesh filename="package://libra/meshes/mount_g-lidar.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${m_lidar_L} ${m_lidar_W} ${m_lidar_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_lidar_m}" x="${m_lidar_L}" y="${m_lidar_W}" z="${m_lidar_H}"/>
        </link>
        <joint name="base_to_mount_lidar" type="fixed">
            <parent link="sensor_suite_base_link"/>
            <child link="mount_lidar_link"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </joint>

        <!-- LIDAR -->
        <link name="lidar_link">
            <visual>
                <origin xyz="0.013602 0 0.028351" rpy="0 0 -${PI/2}"/>
                <geometry>
                    <mesh filename="package://libra/meshes/lidar_sf45b-simplified.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${lidar_H/2}" rpy="0 0 0"/>
                <geometry>
                    <box size="${lidar_L} ${lidar_W} ${lidar_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${lidar_m}" x="${lidar_L}" y="${lidar_W}" z="${lidar_H}"/>
        </link>
        <joint name="mount_lidar_to_lidar" type="fixed">
            <parent link="mount_lidar_link"/>
            <child link="lidar_link"/>
            <origin xyz="0.006 0 0" rpy="0 ${PI/2} 0"/>  <!-- facing downwards -->
        </joint>

        <!-- Camera Mount -->
        <link name="mount_camera_link">
            <visual>
                <origin xyz="0 0 0" rpy="-${PI/2} 0 ${PI/2}"/>
                <geometry>
                    <mesh filename="package://libra/meshes/mount_g-realsense.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.045175 0 0.009540" rpy="0 0 0"/>
                <geometry>
                    <box size="${m_camera_L} ${m_camera_W} ${m_camera_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${m_camera_m}" x="${m_camera_L}" y="${m_camera_W}" z="${m_camera_H}"/>
        </link>
        <joint name="base_to_mount_camera" type="fixed">
            <parent link="sensor_suite_base_link"/>
            <child link="mount_camera_link"/>
            <origin xyz="-0.002 0 0" rpy="0 0 0"/>  <!-- accounts for mounting bracket thickness -->
        </joint>

        <!-- Camera -->
        <link name="camera_link">
            <visual>
                <origin xyz="0.026 0 0" rpy="${PI/2} 0 ${PI/2}"/>
                <geometry>
                    <mesh filename="package://libra/meshes/realsense_d456.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="${camera_L/2} 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${camera_L} ${camera_W} ${camera_H}"/>
                </geometry>
            </collision>
            <xacro:box_inertia m="${camera_m}" x="${camera_L}" y="${camera_W}" z="${camera_H}"/>
        </link>
        <joint name="mount_camera_to_camera" type="fixed">
            <parent link="mount_camera_link"/>
            <child link="camera_link"/>
            <origin xyz="0.068267 0 0" rpy="${PI} 0 0"/>  <!-- upside-down -->
        </joint>

        <!-- ********************[ GAZEBO CONFIG ]******************** -->

        <gazebo reference="mount_lidar_link"><material>Gazebo/Black</material></gazebo>
        <gazebo reference="lidar_link"><material>Gazebo/Blue</material></gazebo>
        <gazebo reference="mount_camera_link"><material>Gazebo/Black</material></gazebo>
        <gazebo reference="camera_link"><material>Gazebo/Blue</material></gazebo>

    </xacro:macro>
</robot>
